config/routes.rb
Glenwoodbroll::Application.routes.draw do
  root :to => "videos#index"
  devise_for :users

  resources :videos
  resources :collections, :only => [:index, :create, :update, :destroy] do
    member do
      post :populate
      post :depopulate
      get :show_build
      post :build
    end
    post :switch, :on => :collection
  end
  resources :categories, :except => [:show]
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :videos

  delegate :empty?, :to => :videos

  validates :user, :name, :presence => true

  def <<(video)
    videos << video unless videos.include?(video)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  load_and_authorize_resource

  def index
  end
  
  # Shows the page that allows the user to build their download
  def show_build
  end

  # Performs the build
  def build
    respond_to do |format|
      format.zip do
        bucket = s3_bucket
        headers['Cache-Control'] = 'no-cache'
        #folder = "test_videos"

        tmp_filename = "#{Rails.root.to_s}/tmp/collection_#{Time.now.to_f.to_s}.zip"

        Zip::ZipFile.open(tmp_filename, Zip::ZipFile::CREATE) do |zip|
          @collection.videos.each do |video|
            s3_object_key = "#{video.file_name}.#{params[:video_format]}"
            tmpfile = Tempfile.new("#{video.file_name}")
            tmpfile.write(bucket.key(s3_object_key).get)
            tmpfile.rewind
            zip.add(s3_object_key, tmpfile.path)
          end
        end

        send_data(File.open(tmp_filename, "rb+").read, :type => 'application/zip', :disposition => 'attachment', :filename => tmp_filename.to_s)
        File.delete tmp_filename
      end
    end
  end

  # Adds a video to the collection
  def populate
    @video = Video.find(params[:video_id])
    render :nothing => true and return if @collection.videos.include? @video
    @collection << @video

    respond_to do |format|
      format.html { redirect_to :back, :notice => "Video added to your reel." }
      format.js
    end
  end

  # Removes a video from the collection
  def depopulate
    @video = Video.find params[:video_id]
    @collection.videos.delete(@video)

    respond_to do |format|
      format.html { redirect_to :back, :notice => "Video removed from your reel." }
      format.js
    end
  end

  # Changes the current collection
  def switch
    @collection = Collection.find params[:collection_id]
    authorize! :read, @collection
    session[:cid] = @collection.id

    respond_to do |format|
      format.html { redirect_to :back, :notice => "Reel changed to #{@collection.name}" }
      format.js
    end
  end

  def create
    @collection.user = current_user
    if @collection.save
      session[:cid] = @collection.id
      redirect_to Video, :notice => 'Reel successfully created'
    else
      redirect_to :back, :alert => 'Reel requires a name'
    end
  end

  def update
    respond_to do |format|
      if @collection.update_attributes params[:collection]
        format.html { redirect_to :back, :notice => 'Reel updated' }
        format.js
      else
        format.html { redirect_to :back, :alert => 'Invalid name' }
        format.js   { render :text => 'alert("Invalid name")' }
      end
    end
  end

  def destroy
    @collection.destroy
    redirect_to Collection, :notice => 'Reel successfully removed'
  end
end

app/helpers/collection_helper.rb
module CollectionHelper
  def link_to_populate(video)
    collection_action('Add To Reel', 'populate', video)
  end

  def link_to_depopulate(video)
    collection_action('Remove', 'depopulate', video)
  end

  def collection_action(text, action, video)
    if current_collection
      path = send("#{action}_collection_path", current_collection, :video_id => video.id)
      options = {:method => :post, :class => 'button', :remote => :true, :id => "#{action}-#{video.id}"}
      button_to(text, path, options)
    end
  end
end

app/views/collections/depopulate.js.erb
$("#<%= @video.id %>").remove();

app/views/collections/populate.js.erb
$("#current_reel_videos").append(
  "<%= escape_javascript(render('shared/current_reel_video', :locals => {:video => @video})) %>"
);

app/views/collections/show_build.html.erb
<h1>Build your Reel</h1>

<%= form_for @collection, :url => build_collection_url(@collection, :zip), :html => {:method => :post}  do |f| %>
  <h2>Select a video format</h2>
  <%= select_tag :video_format, options_for_select(Video.encoding_options) %>

  <h2>Your Videos</h2>
  <ul>
    <% @collection.videos.each do |video| %>
      <li><%= video.title %></li>
    <% end %>
  </ul>

  <%= f.submit "Build" %>
<% end %>

app/views/collections/switch.js.erb
$("#current-reel").html("<%= escape_javascript(render('shared/current_reel')) %>");

app/views/collections/update.js.erb
$("form#switch_collection").html("<%= escape_javascript(select_tag_for_switch_collection) %>");
$("#reel_name").html("<%= escape_javascript(current_collection.reload.name) %>");
$("#current_collection .label").show();
$("#current_collection form").hide();