config/routes.rb
Glenwoodbroll::Application.routes.draw do
  root :to => "videos#index"
  devise_for :users

  resources :videos
  resources :collections, :only => [:index, :create, :update, :destroy] do
    member do
      post :populate
      post :depopulate
      get :show_build
      post :build
    end
    post :switch, :on => :collection
  end
  resources :categories, :except => [:show]
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :collections

  validates :title, :description, :category, :presence => true
  validates :duration, :numericality => {:only_integer => true}, :allow_nil => true

  def self.search(params)
    results = scoped
    results = results.where('title LIKE ? OR description LIKE ?', "%#{params['keywords']}%", "%#{params['keywords']}%") unless params['keywords'].blank?
    results = results.where(:category_id => params['category_id']) unless params['category_id'].blank?
    results
  end

  def self.encoding_options
    [['avi', 'avi'],['mp4','mp4']]
  end

  def flv_url
    "https://s3.amazonaws.com/gsrca-flv/flv/" + self.file_name + ".flv"
  end

  def flv_preview_image
   "https://s3.amazonaws.com/gsrca-flv/flv/" + self.file_name + ".jpg"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  load_and_authorize_resource

  def index
    @videos = @videos.search(search_params)
  end
  
  def show
  end
  
  def new
  	@video_select_options = video_select_options
    flash.now.alert = 'No Videos Available' if @video_select_options.empty?
  end
	
  def create
    if @video.save
      redirect_to @video, :notice => 'Video record was successfully created. Now upload a video!'
    else
      render :new
    end
  end

  def edit
  	@video_select_options = video_select_options
  end
  
  def update
  	if @video.update_attributes(params[:video])
      redirect_to @video, :notice => 'Video record was successfully updated.'
  	else
      render "edit"
  	end
  end
  
  def destroy
    @video.destroy
    redirect_to Video, :notice => 'Video record was deleted.'
  end
  
  private
  
  def video_select_options
    bucket = s3_bucket
    keys = bucket.keys.map(&:to_s)
    keys = keys.select {|k| k =~ /^.*\.avi$/}.map {|k| k.gsub('videos/','').gsub('.avi','')}
    #existing_keys = Video.all.map(&:file_name)
    #keys.reject {|k| existing_keys.include? k}
  end
  
  def search_params
    params.select {|k,v| ['category_id','keywords'].include?(k)}
  end
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>
    <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "Select a category" %><br />
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.select(:file_name, options_for_select(@video_select_options, @video.file_name)) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button left' %>
  </div>
<% end %>

<%= link_to 'Back', :back, :class => 'button left' %>

app/views/videos/_video.html.erb
<li>
  <div class="shadow-box">
    <div class="t">
      <div class="r">
        <div class="b">
          <div class="l">
            <div class="content">
              <h2><%= link_to video.title, video_path(video), :class => 'title' %></h2>
              <div class="actions">
                <%= link_to('Edit', edit_video_path(video), :class => 'button edit') if can?(:edit, video) %> 
                <%= link_to_populate(video) %>
              </div>
              <div class="video-preview">
                <div id="player-<%= video.file_name %>">
                  You need to have <%= link_to 'Flash Player', 'http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash' %> installed to display this video
                </div>

                <script type="text/javascript">
                  var so = new SWFObject('/flash/player.swf', 'mpl', '250', '164', '8');
                  so.addParam('allowscriptaccess', 'always');
                  so.addParam('allowfullscreen', 'true');
                  so.addVariable('height', '164');
                  so.addVariable('width', '250');
                  so.addVariable('file', '<%= video.flv_url %>');
                  so.addVariable('image', '<%= video.flv_preview_image %>');
                  so.write('player-<%= video.file_name %>');
                </script>
              
              </div>
              <table class="video-info">
                <tr>
                  <td class="label">Category:</td>
                  <td><%= video.category.name if !video.category.nil? %></td>
                </tr>
                <tr>
                  <td class="label">Duration:</td>
                  <td><%= video.duration || "N/A" %></td>
                </tr>
                <tr>
                  <td class="label">Posted:</td>
                  <td><%= time_ago_in_words(video.created_at) %> ago</td>
                </tr>
              </table>
              <p><%= video.description %></p>
              <div class="clear"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tl"></div>
    <div class="tr"></div>
    <div class="br"></div>
    <div class="bl"></div>
  </div>
</li>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

app/views/videos/index.html.erb
<h1>GSCRA B-Roll Library</h1>
<% if can?(:create, Video) %>
<div class="admin-toolbar">
<%= link_to('New Video', new_video_path, :class => 'button new')  %>
</div>
<% end %>

<% if @videos.any? %>
  <ul class="video-list">
    <%= render @videos %>
  </ul>
<% else %>
  <div>No Videos Found.</div>
<% end %>

app/views/videos/new.html.erb
<h1>New video</h1>
 
<%= render 'form' %>

app/views/videos/show.html.erb
<div class="search-result-right">
	<h2><%= @video.title %></h2>
	<div class="add_to_collection"><%= link_to_populate(@video) %></div>
	<table class="video-info">
		<tr>
			<td class="label">Category:</td>
			<td><%= @video.category.name %></td>
		</tr>
		<tr>
			<td class="label">Posted:</td>
			<td><%= time_ago_in_words(@video.created_at) %> ago</td>
		</tr>
	</table>
	<p><%= @video.description %></p></div>
<div class="clear"></div>

<%= link_to 'Back', :back, :class => 'button' %>