config/routes.rb
Glenwoodbroll::Application.routes.draw do
  root :to => "videos#index"
  devise_for :users

  resources :videos
  resources :collections, :only => [:index, :create, :update, :destroy] do
    member do
      post :populate
      post :depopulate
      get :show_build
      post :build
    end
    post :switch, :on => :collection
  end
  resources :categories, :except => [:show]
end

app/views/shared/_collection.html.erb
<h2>My Video Reels</h2>
<div id="current_collection">
  <div id="current-reel">
    <%= render 'shared/current_reel' %>
  </div>
</div>

<%= link_to "Build Reel for Download", show_build_collection_path(current_collection), :class => 'button large', :style => 'width:173px;font-size:14px;height:25px;' %>

<h4>Switch Reels</h4>
<% if current_user.collections.count > 1 %>
  <%= form_tag(switch_collections_path, :method => :post, :id => 'switch_collection') do %>
    <%= select_tag_for_switch_collection %>
    <noscript>
      <%= submit_tag "Switch", :id => 'switch_button' %>
    </noscript>
  <% end %>
<% end %>

<h4>Create New Reel</h4>
<%= form_for(Collection.new) do |f| %>
  <%= f.text_field :name, :size => 22 %>
  <%= f.submit 'Create', :class => 'button', :style => 'margin-top:6px;' %>
<% end %>

app/views/shared/_current_reel.html.erb
<span class="tiny-header">Current Reel</span>
<span class="label reel">
  <span id="reel_name"><%= current_collection.name %></span>
  <div class="actions"><%= link_to 'Edit', '#' %></div>
</span>
<%= form_for(current_collection, :remote => true, :html => {:style => 'display:none;'}) do |f| %>
  <%= f.text_field :name, :size => 22 %>
  <%= f.submit 'Update' %>
<% end %>
<div class="clear"></div> 
<div class="videos">
  <span class="tiny-header">Videos</span>
  <span id="current_reel_videos">
    <%= render :partial => 'shared/current_reel_video', :collection => current_collection.videos, :as => :video %>
  </span>
  <% if current_collection.empty? %>
    No Videos Selected
  <% end %>
</div>

app/views/shared/_current_reel_video.html.erb
<% video = @video unless video %>
<span class="video" id="<%= video.id %>"><%= video.title %><%= link_to_depopulate(video) %></span>

app/views/shared/_footer.html.erb
&copy; Glenwood Springs Chamber Resort Association | 1102 Grand Avenue, Glenwood Springs, Colorado 81601

app/views/shared/_header.html.erb
<div id="header">
  <div id="header-menu">
    <ul>
      <li><%= link_to 'Videos', Video if can?(:read, Video) %></li>
      <li><%= link_to 'Categories', Category if can?(:read, Category) %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path if current_user %></li>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<h2>Search</h2>
  <%= form_tag videos_url, :method => :get do |f| %>
  <%= label_tag "Category" %><br />
  <% @options = Category.all.map {|c| [c.name,c.id]} %>
  <% @options.insert(0, ["All Categories",""]) %>
  <%= select_tag :category_id, options_for_select(@options, params[:category_id]) %>
  <%= label_tag "Keywords" %><br />
  <%= text_field_tag :keywords, params[:keywords], :size => 22 %>
  <%= submit_tag "Search Videos", :class => 'button large' %>
<% end %>

app/views/shared/_shadow_box.html.erb
<div id="<%= id %>" class="shadow-box">
  <div class="t">
    <div class="r">
      <div class="b">
        <div class="l">
          <div class="content">
            <%= content %>
          </div>
        </div>
      </div>
    </div>
    <div class="tl"></div>
    <div class="tr"></div>
    <div class="br"></div>
    <div class="bl"></div>
  </div>
</div>

app/views/shared/_sign_in.html.erb
<h2>Sign In</h2>
<%= form_for(User.new, :url => new_user_session_path) do |f| %>
  <%= f.label :email %><br />
  <%= f.email_field :email, :size => '22' %><br />
  <%= f.label :password %><br />
  <%= f.password_field :password, :size => '22' %><br />
  <%= f.check_box :remember_me %><%= f.label :remember_me, :class => 'small' %><br />
  <%= f.submit "Sign In", :class => 'button' %>
  <% link_to "Forgot your password?", new_user_password_path %>
<% end %>

app/views/shared/_video_item.html.erb
<div class="video-line-item">
	<div class="thumb"></div>
	<div class="title">People Shopping Downtown</div>
	<div class="info">Shopping, 0:12 <a class="remove">Remove</a></div>
	<div class="clear"></div>
</div>