config/routes.rb
Glenwoodbroll::Application.routes.draw do
  root :to => "videos#index"
  devise_for :users

  resources :videos
  resources :collections, :only => [:index, :create, :update, :destroy] do
    member do
      post :populate
      post :depopulate
      get :show_build
      post :build
    end
    post :switch, :on => :collection
  end
  resources :categories, :except => [:show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :videos
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def create
    if @category.save
      redirect_to Category, :notice => "Category created."
    else
      render :new
    end
  end

  def update
    if @category.update_attributes(params[:category])
      redirect_to Category, :notice => "Category updated."
    else
      render :edit
    end
  end
  
  def destroy
    @category.destroy
    redirect_to Category, :notice => "Category removed."
  end
  
  def index
  	@categories = Category.all(:order => 'name ASC')
  end
  
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Create', :class => 'button left' %>
  </div>
<% end %>
<%= link_to 'Back', :back, :class => 'button left' %>

app/views/categories/edit.html.erb
<h2>Edit <%= @category.name %></h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Video Categories</h1>
<% if can?(:create, Category) %>
<div class="admin-toolbar">
<%= link_to 'New Category', new_category_path, :class => 'button new long' %>
</div>
<% end %>
<table class="list" width="100%" style="margin-top:10px;" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th>Name</th>
      <th># of Videos</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  	<% count = 0; %>
    <% @categories.each do |category| %>
      <tr class="<%= count % 2 == 0 ? 'even' : 'odd' %>">
        <td><%= category.name %></td>
        <td><%= category.videos.count %></td>
        <td>
        	<div style="float:right; width:200px;">
          <%= link_to 'Edit', edit_category_url(category), :class => 'button right edit' %>
          <%= button_to 'Remove', category_url(category), :method => :delete, :class => 'button right delete' %>
        	</div>
        </td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h2>Create a category</h2>

<%= render 'form' %>